### ISSUE TITLE
Setting Locale... text looks highlighted

### ISSUE THREAD

**Issue by mrichardson23** [raspberrypi-ui/rc_gui#2]
Steps to reproduce:
1. Click localisation tab
2. Click Set Locale button
3. Change the locale to anything else.
4. Click OK

Behavior:
"Setting locale - please wait..." message text looks like it's been highlighted.

**Comment by spl237** [comment]
This "feature" of GTK has now annoyed me so much that I've recreated the alert boxes from individual elements so the text isn't highlighted any more...

(The highlight was because the GTK message box type has the text fields wrongly marked as selectable items; most message boxes have buttons which take the focus, but as mine didn't have buttons, the focus went to the text label and highlighted it. At some point this might get fixed in GTK - it's pretty trivial to rectify.)

**Comment by mrichardson23** [comment]
I'm so glad to hear that I'm not the only one that gets annoyed by that kind of stuff. Thanks for the explanation on these things, it's very helpful for me to try to understand what packages are responsible for what.

**Comment by spl237** [comment]
It's my job to get annoyed by that kind of stuff... :-)
