### ISSUE TITLE
Keyboard layout handler close does nothing

### ISSUE THREAD

**Issue by kz282** [raspberrypi-ui/rc_gui#48]
I have experienced issue #39 on a Pi 4 with a fresh Buster installation with LXPanel 0.10.0.

After editing the Keyboard Layout Handler settings, the new settings are not written to ~/.config/lxpanel/LXDE-pi/panels/panel after clicking the Close button on the dialog. It looks like the close button does nothing.

I have found a workaround:

1. Edit the keyboard layout settings
2. Close the keyboard layout settings / You don't even need to do this...
3. Open the Panel Settings dialog
4. Close the Panel Settings dialog
And the keyboard layout configuration is written to the disk.
Now the settings survive shutdown / restart, reboot etc.

**Comment by spl237** [comment]
We do not recommend or support the use of the Keyboard Layout Handler settings plugin for the taskbar, which is why it is not on the taskbar by default. It will almost certainly conflict with the correct mechanism for setting the keyboard layout, which is to use either the Keyboard Layout button on the Keyboard tab of the Mouse & Keyboard settings application, or the Set Keyboard button on the Localisation tab of the Raspberry Pi Configuration application, or via the startup wizard. All of these write the selected keyboard setting to the global system keyboard file, which is where it needs to be to take effect in all terminals and applications.

**Comment by kz282** [comment]
I have checked those options, but neither offers the option of showing the current layout on the taskbar and changing the layout with one click or one key combination.

What is the preferred way to do these?
