### ISSUE TITLE
How to build on aarch64?

### ISSUE THREAD

**Issue by GITNE** [raspberrypi-ui/rc_gui#60]
Hello @spl237,

I have a bunch of code updates, mostly regarding cosmetic consistency, pending for rc_gui. However, when I try to build rc_gui targeting aarch64 I am lacking the `glibconfig.h` header file for that architecture. I cannot find any dev package containing it in Raspberry Pi OS’s repo, and yet rc_gui has obviously been built for aarch64 (because this is what I have been running most of the time). I am just wondering how the guys or gals have built rc_gui without having that file. I mean, sure I could kinda *rebuild* the `libglib2.0-dev` package for aarch64 myself but that’s way too much hassle for me and probably not the right way to go. If you would be so kind to ask the guy or gal who built the aarch64 Raspberry Pi OS beta to also upload that `libglib2.0-dev` (and potentially also the `libgtk2.0-dev` package) I would be happy to be able to complete my PR. Or, maybe I a missing something and perhaps you could give me a hint? Anyways, thank you!

**Comment by spl237** [comment]
I should probably warn you that from what you say, I am unlikely to accept a PR with the code updates you describe above.

I accept PRs with new translations - and thank you very much for those you have already submitted! - and with fixes for known bugs. I regard anything else - such as the cosmetic changes you describe - as introducing unnecessary change and hence unnecessary risk. However well-intentioned, any change to code carries the risk of introducing new bugs. Further, with all the applications that I have written, the responsibility for maintenance and bug fixing is mine alone, and if a bug is introduced in a new release, I am the one who gets blamed, and I am the one who has to fix it! In the past, I have accepted PRs which looked innocuous enough, but then turned out to cause subtle issues, and as a result, my policy now is that if code works, I don't change it.

My apologies if you have already put significant effort into changes, but I felt I should let you know of my position on this. I should also mention that the next release of rc_gui (which is imminent with the bullseye release of RPiOS) is based on GTK+3 rather than GTK+2, which (given your mention of libgtk2.0-dev) may well render any changes you have made obsolete anyway.

**Comment by GITNE** [comment]
> I should probably warn you that from what you say, I am unlikely to accept a PR 
> with the code updates you describe above.

Well, thank you, I guess…?

> I accept PRs with new translations - and thank you very much for those you have 
> already submitted! - and with fixes for known bugs. I regard anything else - 
> such as the cosmetic changes you describe - as introducing unnecessary change 
> and hence unnecessary risk. However well-intentioned, any change to code carries 
> the risk of introducing new bugs. Further, with all the applications that I have 
> written, the responsibility for maintenance and bug fixing is mine alone, and if 
> a bug is introduced in a new release, I am the one who gets blamed, and I am the 
> one who has to fix it! In the past, I have accepted PRs which looked innocuous 
> enough, but then turned out to cause subtle issues, and as a result, my policy 
> now is that if code works, I don't change it.

I mean no offense but this attitude kind of kills any open source collaboration model and also any progress and innovation. Being a maintainer does not mean that that the only person who can or should fix bugs is you nor that you are responsible for everything that goes wrong or well. Being a maintainer in the open source world means to be a good custodian. It means that your job is to leverage from the community what is good for the thing you are maintaining. Given your past experience with some ill crafted contributions I do understand that you might be hesitant to accept any further contributions but the only antidote to your fear are review and testing. And, this is exactly what I am doing. Everything in life is risky and sometimes things do not always go as intended. However, if you do not let risk into your life, in other words, if you do not take chances in life you will not learn anything new and will just stagnate. So, what usually helps not only in software development but also in life in general is to learn from mistakes and concentrate more on the good things, the things that went well in the past but also those that could go even better in the future. Do not let you personal grievances interfere with your job or professional judgement. I can only hope that you will reevaluate you posture. 

> My apologies if you have already put significant effort into changes, but I felt 
> I should let you know of my position on this. I should also mention that the 
> next release of rc_gui (which is imminent with the bullseye release of RPiOS) is 
> based on GTK+3 rather than GTK+2, which (given your mention of libgtk2.0-dev) 
> may well render any changes you have made obsolete anyway.

As I said, my intended changes were not significant; that’s why I called them cosmetic. However, I believe consistency does matter. 

I was to add further translations and consistency fixes to other packages and areas of the Raspberry Pi OS but as it stands now I think I might have had enough for the foreseeable future. Good luck!
